[package]
name = "brother_betting"
version = "0.1.0"

[dependencies]
starknet = ">=2.3.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.12.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"